- id: black
  name: black
  description: "Black: The uncompromising Python code formatter"
  entry: black
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  stages: [commit]
- id: flake8
  name: flake8
  description: "Flake8: The uncompromising Python code linter"
  entry: flake8
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  stages: [commit]